#! /usr/bin/env ruby

require_relative "../lib/campaign_tech"

logger = Logger.new(STDOUT)
crawler = CampaignTech.new

logger.info "Starting crawl..."
crawler.crawl
logger.info "Crawl complete."

logger.info "Updating CSV..."
crawler.write_to_csv

logger.info "Fin."
puts crawler.overview
